import type { NextPage } from "next";
import Head from "next/head";
import Grid from "@mui/material/Grid";
import Jumbotron from "../components/Jumbotron";
import Carousel from "../components/carousel/Carousel";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid
          container
          spacing={1}
          component="div"
          sx={{ mb: 3 }}
          justifyContent="space-between"
        >
          <Grid item xs={12}>
            <div>
              <Jumbotron />
            </div>
            <div>
              <Carousel />
            </div>
            <Button variant="contained">Hello World</Button>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
